version: '3.0'
services:
  mongo-db-nest:
    container_name: mongo-db-nest
    image: mongo:5.0
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ~/apps/nestjs:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
